version: '2'
services:
  db:
    image: mysql
    container_name: film_db
    ports: 
      - 3306:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: film_db
  mywebsite:
    image: 
    container_name: website
    volumes:
      - /app/filmfront/dist:/var/www/html
    #build:
      #context: ./
    ports:
    - 80:80   # http
    #- 443:443 # permet https mais il faudra un ssl sur apache...
  myadmin:
    image: adminer
    container_name: myadminer
    ports:
    - 8080:8080